[versions]
##########################################################################
# Plugins
# Check this on https://kotlinlang.org/docs/releases.html
kotlin = "2.2.21"
# Check this on https://github.com/Kotlin/dokka/releases/latest/
dokka = "2.1.0"
# Check this on https://plugins.gradle.org/plugin/dev.yumi.gradle.licenser/
yumiGradleLicenser = "2.2.1"
# Check this on https://plugins.gradle.org/plugin/co.uzzu.dotenv.gradle/
dotenv = "4.0.0"
# Check this on https://github.com/GradleUp/nmcp/releases/latest/
nmcp = "1.3.0"
##########################################################################
# Java Configuration
# The Java version the JDK will be for compiling and running code.
java = "17"
# The Java version the JDK will be for running Gradle.
gradleJava = "25"
##########################################################################
# Dependency
# Check this on https://central.sonatype.com/artifact/org.slf4j/slf4j-api/
slf4j = "2.0.17"
# Check this on https://central.sonatype.com/artifact/org.junit.jupiter/junit-jupiter-api/
junit = "6.0.1"
##########################################################################
[libraries]
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
yumiGradleLicenser = { id = "dev.yumi.gradle.licenser", version.ref = "yumiGradleLicenser" }
dotenv = { id = "co.uzzu.dotenv.gradle", version.ref = "dotenv" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
